In [1]:
#for nested loop
for outer_loop in range(1,4):
    for inner_loop in "ABC":
        print(outer_loop, inner_loop)
    

1 A
1 B
1 C
2 A
2 B
2 C
3 A
3 B
3 C


In [2]:
num=0
while num < 7:
    print(num)
    num=num+1

0
1
2
3
4
5
6


In [6]:
#jump statement in python(break,continue and pass)
for i in range(1,10):
    if i==5:
        break
    print("number is" + " " + str(i))
print('out of loop')


number is 1
number is 2
number is 3
number is 4
out of loop


In [15]:
password ="tuesday"

for trail in range(5):
    if trail == 4:
        print("one trail left")
    enter_password=input("enter password:")
    if enter_password == password:
        print("wlcome to python")
        break
    else:
        print("wrong Password")

    

enter password: asd


wrong Password


enter password: tuesday


wlcome to python


In [18]:
otp="naman"
for trail in range(1,4):
    if trail == 4:
        print("one trail left")
    enter_otp =input("enter otp")
    if enter_otp != otp:
        print("try again")
        continue
    else:
        name= input("enter your name")
        city_name=input("Enter your city")
        break

enter otp adffa


try again


enter otp naman
enter your name raman
Enter your city sasaram


In [1]:
### fuction 
def welcome():
    print("welocome to the python")
welcome()

welocome to the python


In [3]:
def add_number():
    total=4+2
    print("sum of 2 and 4 is :", total)
    return total


sum of 2 and 4 is : 6


6

In [4]:
output=add_number()

sum of 2 and 4 is : 6


In [5]:
output

6

function with parametes

In [7]:
def welcome(name):
    return "welcome to python course,"+ name
welcome("parsant")

'welcome to python course,parsant'

In [8]:
output_1=welcome("mohan")


In [10]:
output_1

'welcome to python course,mohan'

In [11]:
#default values of parameters
def welcome(name='Aravinf'):
    return "welcome to python course,"+name
welcome("rohan")


'welcome to python course,rohan'

position arguments

In [14]:
def math_functions(small_number, large_number):
    difference=large_number-small_number
    return difference
math_functions(8,6)

-2

In [15]:
math_functions(6,8)

2

keyword arguments

In [18]:
math_functions(large_number=16, small_number=4)

12

In [19]:
math_functions(small_number=4, large_number=16)

12

In [21]:
math_functions(6, large_number=16)

10

In [22]:
math_functions(small_number=6, 16)

SyntaxError: positional argument follows keyword argument (1029540012.py, line 1)

In [ ]:
# because python always define the positional arguments before the keyword arguments

scope of variable:local and global variables

In [24]:
name="variable outside function"
def my_function():
    return name*3
my_function()

'variable outside functionvariable outside functionvariable outside function'

In [27]:
name="function outside of varible"
def my_function():
    name="variable inside function"
    return name

In [28]:
my_function() #if will consider the first inside(local varible))

'variable inside function'

In [1]:
my_list=[i**2 for i in range(10)]
print(my_list)## list comprenhsionn

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [7]:
data=['a','b','c']
index=0
for i in data :
    print(index,i) # not good
    index +=1

0 a
1 b
2 c


In [13]:
# using the enumerate function for the indics
data1=['c','b','d']
index=0
for index, item in enumerate(data1):
    print(index,item) # it is used for the both index and item generate and that would be tuple

0 c
1 b
2 d


pep 8 and pep 257 style guideline

In [ ]:
# bad code : usese single-letter varibles or unclear names.

x=10
y=20
z=x*y

#good code: use descriptive variable name in snake_case
width=10
height=20
area= width* height

funtion nameing conventions


In [ ]:
# bad code: uses camelCase or unclear function names
def CalculateArea():
    pass
def calc():

#good code :uses desriptive function names in snake_case
def calculate_area():
    pass
def calculate_total_price():
    pass

constant nameing cinventions

#bad code:uses lowercase or unclear nameing
pi_value=3.1415
discountRate=0.1

#good code: use Uppercase letters with underscore for constants
PI=3.1415
DISCOUNT_RATE=0.1


#numpy 



In [2]:
import numpy as np
list_data=[1,4,3,13,45]
arr_from_list=np.array(list_data)
print(arr_from_list)

[ 1  4  3 13 45]


In [3]:
arr_zeros=np.zeros((2,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
arr_ones=np.ones((2,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arr_ones.shape

(2, 3)

In [6]:
arr_ones.ndim

2

In [8]:
#creating an array with arange
arr_arange=np.arange(5,15,2) #start=5, stop=15,set=2)
print(arr_arange) 

[ 5  7  9 11 13]


In [9]:
#creating an array with linspace
arr_linspace=np.linspace(0,1,5) # 5 points from 0 to 1 inclusive
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


##indexing and slicing


In [10]:
arr_1d=np.array([10,20,30,40])
print(arr_1d)

[10 20 30 40]


In [13]:
# slicing
slide_id=arr_1d[1:4]
print(slide_id)

[20 30 40]


In [15]:
arr_2d=np.array([[1,2,3,4],[1,3,2,1],[2,3,4,5]])
print(arr_2d)

[[1 2 3 4]
 [1 3 2 1]
 [2 3 4 5]]


In [16]:
print(arr_2d[1,2]) # remember , rows and cols are 0-indexed)

2


In [17]:
print(arr_2d[0:2,1:3])

[[2 3]
 [3 2]]


In [19]:
indices=[0,2]
arr_fancy=arr_2d[indices,:]
print(arr_fancy)

[[1 2 3 4]
 [2 3 4 5]]


In [21]:
#Boolean indexing 
bool_mask=arr_2d>4
print(bool_mask)

[[False False False False]
 [False False False False]
 [False False False  True]]


In [22]:
##shape for the function 
matrix=np.arange(1,13)
matrix=matrix.reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
 #reshaped
reshaped=matrix.reshape(2,6)
print(reshaped)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
revealed=matrix.ravel()
print(revealed)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
# transpose means change the row to column
transposed=matrix.transpose()
print(transposed)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [27]:
float_arr=np.array([1.2,4.4,6.3,7.5])
print(float_arr)

[1.2 4.4 6.3 7.5]


In [28]:
print(float_arr.dtype)

float64


In [29]:
arr_int=float_arr.astype(np.int64)
print(arr_int)

[1 4 6 7]


In [3]:
#arthemetic problem
import numpy as np
x=np.array([1,2,3,4])
y=np.array([12,13,23,15])
print("ADD:", np.subtract(x,y))


ADD: [-11 -11 -20 -11]


In [4]:
arr_for_log=np.array([1,np.e,100])
print(arr_for_log)

[  1.           2.71828183 100.        ]


In [5]:
np.log(arr_for_log)

array([0.        , 1.        , 4.60517019])

In [6]:
np.log2(arr_for_log)

array([0.        , 1.44269504, 6.64385619])

In [7]:
np.log10(arr_for_log)

array([0.        , 0.43429448, 2.        ])

In [8]:
np.e,np.exp(1) # used to power raise

(2.718281828459045, np.float64(2.718281828459045))

In [9]:
arr_power=np.array([2,3,4])
print(np.power(arr_power,2))
print(np.exp(arr_power)) # it raise the e2,e3,e4. 

[ 4  9 16]
[ 7.3890561  20.08553692 54.59815003]


In [10]:
#Trigonometric & Hyperbolic functions
angles=np.array([0,np.pi/2,np.pi])
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [11]:
#Rounding & other Element-wise Numerics Ufuncs
data_values=np.array([-1.75,-0.22,0.58,1.91,2.57])
print(np.abs(data_values))
print(np.sign(data_values))

[1.75 0.22 0.58 1.91 2.57]
[-1. -1.  1.  1.  1.]


In [13]:
print(np.round(data_values))# it will use for the nearest 
print(np.floor(data_values)) # it will use for the lower integer
print(np.ceil(data_values)) #it will round to the heigher integer
print(np.trunc(data_values)) # it will remove the decimal

[-2. -0.  1.  2.  3.]
[-2. -1.  0.  1.  2.]
[-1. -0.  1.  2.  3.]
[-1. -0.  0.  1.  2.]


In [14]:
# Comparsion and logical Ufuncs
a=np.array([1,2,3,4])
b=np.array([2,2,2,2])
print(np.less(a,b))
print(np.greater_equal(a,b))
print(np.equal(a,b))
print(np.not_equal(a,b))

[ True False False False]
[False  True  True  True]
[False  True False False]
[ True False  True  True]


In [16]:
cond1=a>1
cond2=a<4
print(cond1)
print(cond2)
print(np.logical_and(cond1,cond2))

[False  True  True  True]
[ True  True  True False]
[False  True  True False]


In [18]:
#Statical & Aggregation Function
stats_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(stats_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(np.sum(stats_arr))
print(np.mean(stats_arr))
print(np.std(stats_arr))
print(np.var(stats_arr))


45
5.0
2.581988897471611
6.666666666666667


In [21]:
print(np.argmin(stats_arr))
print(np.argmax(stats_arr)) # according to index it will provide the minimun value and max value

0
8


In [23]:
print(np.median(stats_arr))
print(np.quantile(stats_arr,0.25))

5.0
3.0


In [22]:
print(np.sum(stats_arr,axis=1))
print(np.sum(stats_arr,axis=0))

[ 6 15 24]
[12 15 18]


In [24]:
# Broadcasting
arr_b=np.array([1,2,3])
print("original array:", arr_b)
print(arr_b + 10)

original array: [1 2 3]
[11 12 13]


In [25]:
mat_b1=np.array([[1],[2],[3]])
mat_b2=np.array([10,20,30])
print(mat_b1 +mat_b2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [26]:
# Linear Algebra with numppy.linalg

In [27]:
a=np.array([[1,2],[2,3]])
b=np.array([[2,0],[1,2]])
print(a @ b)

[[4 4]
 [7 6]]


In [28]:
print(b @ a)

[[2 4]
 [5 8]]


In [29]:
a.dot(b)

array([[4, 4],
       [7, 6]])

In [30]:
np.matmul(a,b)

array([[4, 4],
       [7, 6]])

In [32]:
inv_a=np.linalg.inv(a)
inv_b=np.linalg.inv(b)
det_a=np.linalg.det(a)
print(det_a)
print(inv_a)
print(inv_b)

-1.0
[[-3.  2.]
 [ 2. -1.]]
[[ 0.5   0.  ]
 [-0.25  0.5 ]]


In [36]:
#NUmpy Random Module
import numpy as np

rng = np.random.default_rng()

rand_ints = rng.random(5)
print(rand_ints)

[0.81570886 0.63090581 0.8557239  0.02392701 0.1712079 ]


In [37]:
rand_ints=rng.integers(low=0,high=10,size=5)
print(rand_ints)


[2 1 0 1 9]


In [38]:
rand_norm=rng.normal(loc=0,scale=1,size=5)
print(rand_norm)

[-0.52295811 -0.94419744  2.15702641  0.24101384 -0.01355467]


In [46]:
a=np.array([1,2,3,4,5])
rng.shuffle(a)
print(a)

[2 1 4 5 3]


In [47]:
b=np.array([10,20,30,29])
print(rng.permutation(b))

[10 30 29 20]
